In [251]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
from faker import Faker
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, KFold, cross_val_predict, GridSearchCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.datasets import load_digits
from adspy_shared_utilities import plot_feature_importances
import matplotlib.pyplot as plt
fake = Faker()
digits = load_digits

In [322]:
df = pd.read_csv('D:/talent.csv', sep=';')

In [323]:
df.head()

,id,prenom,nom,genre,age,background,cohorte,tauxPart,visiPlat,discussion,noteTalent,noteInst,retards,absences,parti
0,3711,Michael,Robinson,F,18,Master 1,cohorte 5,29,16,20,19,2,Dessous-7,Dessus-3,1
1,7613,Kyle,Miller,M,18,Licence 3,cohorte 7,24,20,25,18,13,Dessous-7,Dessus-3,0
2,4420,Jennifer,Christensen,M,18,Master 1,cohorte 7,14,7,30,16,1,Dessus-7,Dessus-3,1
3,4940,John,Smith,M,24,Licence 3,cohorte 5,24,25,35,17,7,Dessus-7,Dessus-3,0
4,5320,Diana,Hunter,M,18,Licence 3,cohorte 6,38,50,50,6,5,Dessus-7,Dessous-3,0

In [232]:
df.corr(method='spearman').style.format("{:.2}").background_gradient(cmap=plt.get_cmap('coolwarm'))

In [5]:
genre= pd.get_dummies(df["genre"])
genre.head()

   F  M
0  1  0
1  0  1
2  0  1
3  0  1
4  0  1

In [6]:
df = pd.concat([df, genre], axis=1)
df[['genre', 'F', 'M']].head()

  genre  F  M
0     F  1  0
1     M  0  1
2     M  0  1
3     M  0  1
4     M  0  1

In [7]:
df.head()

,id,prenom,nom,genre,age,background,cohorte,tauxPart,visiPlat,discussion,noteTalent,noteInst,retards,absences,parti,F,M
0,3711,Michael,Robinson,F,18,Master 1,cohorte 5,29,16,20,19,2,Dessous-7,Dessus-3,1,1,0
1,7613,Kyle,Miller,M,18,Licence 3,cohorte 7,24,20,25,18,13,Dessous-7,Dessus-3,0,0,1
2,4420,Jennifer,Christensen,M,18,Master 1,cohorte 7,14,7,30,16,1,Dessus-7,Dessus-3,1,0,1
3,4940,John,Smith,M,24,Licence 3,cohorte 5,24,25,35,17,7,Dessus-7,Dessus-3,0,0,1
4,5320,Diana,Hunter,M,18,Licence 3,cohorte 6,38,50,50,6,5,Dessus-7,Dessous-3,0,0,1

In [8]:
background= pd.get_dummies(df["background"])
background.head()

   Licence 3  Master 1  Master 2
0          0         1         0
1          1         0         0
2          0         1         0
3          1         0         0
4          1         0         0

In [9]:
df = pd.concat([df, background], axis=1)
df[['background', 'Licence 3', 'Master 1', 'Master 2']].head()

  background  Licence 3  Master 1  Master 2
0   Master 1          0         1         0
1  Licence 3          1         0         0
2   Master 1          0         1         0
3  Licence 3          1         0         0
4  Licence 3          1         0         0

In [10]:
df.head()

,id,prenom,nom,genre,age,background,cohorte,tauxPart,visiPlat,discussion,noteTalent,noteInst,retards,absences,parti,F,M,Licence 3,Master 1,Master 2
0,3711,Michael,Robinson,F,18,Master 1,cohorte 5,29,16,20,19,2,Dessous-7,Dessus-3,1,1,0,0,1,0
1,7613,Kyle,Miller,M,18,Licence 3,cohorte 7,24,20,25,18,13,Dessous-7,Dessus-3,0,0,1,1,0,0
2,4420,Jennifer,Christensen,M,18,Master 1,cohorte 7,14,7,30,16,1,Dessus-7,Dessus-3,1,0,1,0,1,0
3,4940,John,Smith,M,24,Licence 3,cohorte 5,24,25,35,17,7,Dessus-7,Dessus-3,0,0,1,1,0,0
4,5320,Diana,Hunter,M,18,Licence 3,cohorte 6,38,50,50,6,5,Dessus-7,Dessous-3,0,0,1,1,0,0

In [11]:
cohorte= pd.get_dummies(df["cohorte"])
cohorte.head()

   cohorte 5  cohorte 6  cohorte 7
0          1          0          0
1          0          0          1
2          0          0          1
3          1          0          0
4          0          1          0

In [12]:
df = pd.concat([df, cohorte], axis=1)
df[['cohorte', 'cohorte 5', 'cohorte 6', 'cohorte 7']].head()

     cohorte  cohorte 5  cohorte 6  cohorte 7
0  cohorte 5          1          0          0
1  cohorte 7          0          0          1
2  cohorte 7          0          0          1
3  cohorte 5          1          0          0
4  cohorte 6          0          1          0

In [267]:
df.head()

,age,tauxPart,visiPlat,discussion,noteTalent,noteInst,parti,F,M,Licence 3,Master 1,Master 2,cohorte 5,cohorte 6,cohorte 7,Dessous-7,Dessus-7,Dessous-3,Dessus-3
0,18,29,16,20,19,2,1,1,0,0,1,0,1,0,0,1,0,0,1
1,18,24,20,25,18,13,0,0,1,1,0,0,0,0,1,1,0,0,1
2,18,14,7,30,16,1,1,0,1,0,1,0,0,0,1,0,1,0,1
3,24,24,25,35,17,7,0,0,1,1,0,0,1,0,0,0,1,0,1
4,18,38,50,50,6,5,0,0,1,1,0,0,0,1,0,0,1,1,0

In [14]:
retards= pd.get_dummies(df["retards"])
retards.head()

   Dessous-7  Dessus-7
0          1         0
1          1         0
2          0         1
3          0         1
4          0         1

In [15]:
df = pd.concat([df, retards], axis=1)
df[['retards', 'Dessous-7', 'Dessus-7']].head()

     retards  Dessous-7  Dessus-7
0  Dessous-7          1         0
1  Dessous-7          1         0
2   Dessus-7          0         1
3   Dessus-7          0         1
4   Dessus-7          0         1

In [266]:
df.head()

,age,tauxPart,visiPlat,discussion,noteTalent,noteInst,parti,F,M,Licence 3,Master 1,Master 2,cohorte 5,cohorte 6,cohorte 7,Dessous-7,Dessus-7,Dessous-3,Dessus-3
0,18,29,16,20,19,2,1,1,0,0,1,0,1,0,0,1,0,0,1
1,18,24,20,25,18,13,0,0,1,1,0,0,0,0,1,1,0,0,1
2,18,14,7,30,16,1,1,0,1,0,1,0,0,0,1,0,1,0,1
3,24,24,25,35,17,7,0,0,1,1,0,0,1,0,0,0,1,0,1
4,18,38,50,50,6,5,0,0,1,1,0,0,0,1,0,0,1,1,0

In [17]:
absences= pd.get_dummies(df["absences"])
absences.head()

   Dessous-3  Dessus-3
0          0         1
1          0         1
2          0         1
3          0         1
4          1         0

In [18]:
df = pd.concat([df, absences], axis=1)
df[['absences', 'Dessous-3', 'Dessus-3']].head()

    absences  Dessous-3  Dessus-3
0   Dessus-3          0         1
1   Dessus-3          0         1
2   Dessus-3          0         1
3   Dessus-3          0         1
4  Dessous-3          1         0

In [264]:
df.head()

,age,tauxPart,visiPlat,discussion,noteTalent,noteInst,parti,F,M,Licence 3,Master 1,Master 2,cohorte 5,cohorte 6,cohorte 7,Dessous-7,Dessus-7,Dessous-3,Dessus-3
0,18,29,16,20,19,2,1,1,0,0,1,0,1,0,0,1,0,0,1
1,18,24,20,25,18,13,0,0,1,1,0,0,0,0,1,1,0,0,1
2,18,14,7,30,16,1,1,0,1,0,1,0,0,0,1,0,1,0,1
3,24,24,25,35,17,7,0,0,1,1,0,0,1,0,0,0,1,0,1
4,18,38,50,50,6,5,0,0,1,1,0,0,0,1,0,0,1,1,0

In [265]:
id = df["id"]
prenom = df["prenom"]
nom = df["nom"]
genre = df["genre"]
background = df["background"]
cohorte = df["cohorte"]
retards = df["retards"]
absences = df["absences"]

KeyError: 'id'

In [21]:

del df["prenom"]
del df["nom"]
del df["genre"]
del df["background"]
del df["cohorte"]
del df["retards"]
del df["absences"]

In [22]:
df.head()

,age,tauxPart,visiPlat,discussion,noteTalent,noteInst,parti,F,M,Licence 3,Master 1,Master 2,cohorte 5,cohorte 6,cohorte 7,Dessous-7,Dessus-7,Dessous-3,Dessus-3
0,18,29,16,20,19,2,1,1,0,0,1,0,1,0,0,1,0,0,1
1,18,24,20,25,18,13,0,0,1,1,0,0,0,0,1,1,0,0,1
2,18,14,7,30,16,1,1,0,1,0,1,0,0,0,1,0,1,0,1
3,24,24,25,35,17,7,0,0,1,1,0,0,1,0,0,0,1,0,1
4,18,38,50,50,6,5,0,0,1,1,0,0,0,1,0,0,1,1,0

In [268]:
df = pd.concat([df, id], axis=1)

In [269]:
df.head()

,age,tauxPart,visiPlat,discussion,noteTalent,noteInst,parti,F,M,Licence 3,Master 1,Master 2,cohorte 5,cohorte 6,cohorte 7,Dessous-7,Dessus-7,Dessous-3,Dessus-3,id
0,18,29,16,20,19,2,1,1,0,0,1,0,1,0,0,1,0,0,1,3711
1,18,24,20,25,18,13,0,0,1,1,0,0,0,0,1,1,0,0,1,7613
2,18,14,7,30,16,1,1,0,1,0,1,0,0,0,1,0,1,0,1,4420
3,24,24,25,35,17,7,0,0,1,1,0,0,1,0,0,0,1,0,1,4940
4,18,38,50,50,6,5,0,0,1,1,0,0,0,1,0,0,1,1,0,5320

In [270]:
feat = df.drop(columns=['parti'],axis=1)
label = df["parti"]

In [293]:
X_train, X_test, y_train, y_test = train_test_split(feat, label, test_size=0.3, shuffle=True)

In [272]:
sgd = linear_model.SGDClassifier(max_iter = 1000, tol=0)
sgd = sgd.fit(X_train, y_train)

In [273]:
prediction = sgd.predict(X_train)

accuracy_train = accuracy_score(y_train, prediction)
accuracy_train

0.8114285714285714

In [274]:
prediction = sgd.predict(X_test)

accuracy_test = accuracy_score(y_test, prediction)
accuracy_test

0.7533333333333333

In [275]:
import math
resultats_exp = pd.DataFrame({"Modèle": [], "Train": [], "Test": [], "Delta": []})

def add_score(nom, acc_train, acc_test):
    resultats_exp.loc[len(resultats_exp)] = [nom, acc_train, acc_test, math.fabs(acc_train-acc_test)]
    return resultats_exp

add_score("Linéaire", accuracy_train, accuracy_test)

     Modèle     Train      Test     Delta
0  Linéaire  0.811429  0.753333  0.058095

# Création d'arbre de décision

In [276]:
clf = RandomForestClassifier(max_depth=6, n_estimators=100)
clf = clf.fit(X_train, y_train)

In [277]:
prediction = clf.predict(X_train)

accuracy_train = accuracy_score(y_train, prediction)
accuracy_train

0.8514285714285714

In [278]:
prediction = clf.predict(X_test)

accuracy_test = accuracy_score(y_test, prediction)
accuracy_test

0.76

In [279]:
scores = cross_val_score(clf, feat, label, cv=5, scoring='f1_macro')
scores

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

array([0.47502825, 0.44198895, 0.44444444, 0.44382022, 0.4375    ])

In [280]:
scores = []
best_svr = SVR(kernel='rbf')
kf = KFold(n_splits=3, random_state=None, shuffle=False)
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]

In [281]:
def get_scores(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [282]:
scores = []
folds = StratifiedKFold(n_splits=3)
kf = KFold(n_splits=3, random_state=None, shuffle=False)
for train_index, test_index in kf.split(feat):
    X_train, X_test, y_train, y_test = feat[train_index], feat[test_index], label[train_index], label[test_index]
    print(get_scores(clf, X_train, X_test, y_train, y_test))

KeyError: "None of [Int64Index([167, 168, 169, 170, 171, 172, 173, 174, 175, 176,\n            ...\n            490, 491, 492, 493, 494, 495, 496, 497, 498, 499],\n           dtype='int64', length=333)] are in the [columns]"

In [283]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, prediction))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, prediction))
print('\n')
print("=== All AUC Scores ===")
print(clf_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", clf_cv_score.mean())

=== Confusion Matrix ===
[[114   0]
 [ 36   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.76      1.00      0.86       114
           1       0.00      0.00      0.00        36

   micro avg       0.76      0.76      0.76       150
   macro avg       0.38      0.50      0.43       150
weighted avg       0.58      0.76      0.66       150



=== All AUC Scores ===
[0.55909091 0.41363636 0.4025     0.5825     0.6125     0.54
 0.435      0.455      0.53076923 0.54871795]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.5079714452214452

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [284]:
grid_values = {'n_estimators': [1000]}
grid_clf_acc = GridSearchCV(clf, param_grid=grid_values, scoring='roc_auc', n_jobs=1, cv=10)
grid_clf_acc.fit(X_train, y_train)
y_decisions_fn_scores_acc = grid_clf_acc.predict(X_test)
print("Best parametres:", grid_clf_acc.best_params_)
print("Best score:", grid_clf_acc.best_score_)
print('Test:', y_decisions_fn_scores_acc)

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

Best parametres: {'n_estimators': 1000}
Best score: 0.47985808116349987
Test: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]

In [285]:

print(clf.feature_importances_)

[0.11512261 0.12562952 0.11333692 0.12375398 0.08791796 0.1146256
 0.00988379 0.01246356 0.01596853 0.01625318 0.01506094 0.02770246
 0.02042651 0.0124403  0.01686575 0.01552297 0.01825317 0.00979627
 0.128976  ]

In [296]:
probs = clf.predict_proba(X_test)
probs

array([[0.85221274, 0.14778726],
       [0.85169128, 0.14830872],
       [0.82373962, 0.17626038],
       [0.54002377, 0.45997623],
       [0.80967683, 0.19032317],
       [0.88570618, 0.11429382],
       [0.92439275, 0.07560725],
       [0.64637926, 0.35362074],
       [0.56797352, 0.43202648],
       [0.79944951, 0.20055049],
       [0.89615228, 0.10384772],
       [0.3460514 , 0.6539486 ],
       [0.73841238, 0.26158762],
       [0.4385066 , 0.5614934 ],
       [0.8693014 , 0.1306986 ],
       [0.32401184, 0.67598816],
       [0.83415784, 0.16584216],
       [0.6844677 , 0.3155323 ],
       [0.68042486, 0.31957514],
       [0.63635885, 0.36364115],
       [0.86599482, 0.13400518],
       [0.46642986, 0.53357014],
       [0.54988044, 0.45011956],
       [0.84438962, 0.15561038],
       [0.55640882, 0.44359118],
       [0.84857253, 0.15142747],
       [0.86898854, 0.13101146],
       [0.62946519, 0.37053481],
       [0.77046186, 0.22953814],
       [0.87006862, 0.12993138],
       [0.79855383, 0.20144617],
       [0.79559591, 0.20440409],
       [0.84580619, 0.15419381],
       [0.88232413, 0.11767587],
       [0.88149966, 0.11850034],
       [0.90156522, 0.09843478],
       [0.88204781, 0.11795219],
       [0.90584763, 0.09415237],
       [0.90367552, 0.09632448],
       [0.89627754, 0.10372246],
       [0.93326606, 0.06673394],
       [0.85948208, 0.14051792],
       [0.85892591, 0.14107409],
       [0.83757477, 0.16242523],
       [0.8187492 , 0.1812508 ],
       [0.88691547, 0.11308453],
       [0.84953372, 0.15046628],
       [0.92130909, 0.07869091],
       [0.88174516, 0.11825484],
       [0.8273095 , 0.1726905 ],
       [0.86678266, 0.13321734],
       [0.85409257, 0.14590743],
       [0.86979344, 0.13020656],
       [0.91997417, 0.08002583],
       [0.88585133, 0.11414867],
       [0.84471671, 0.15528329],
       [0.89201236, 0.10798764],
       [0.88895862, 0.11104138],
       [0.81019498, 0.18980502],
       [0.84743189, 0.15256811],
       [0.89580631, 0.10419369],
       [0.7893917 , 0.2106083 ],
       [0.89124259, 0.10875741],
       [0.84717186, 0.15282814],
       [0.9005902 , 0.0994098 ],
       [0.79917252, 0.20082748],
       [0.92960045, 0.07039955],
       [0.67222163, 0.32777837],
       [0.82610664, 0.17389336],
       [0.79740422, 0.20259578],
       [0.89707219, 0.10292781],
       [0.85230736, 0.14769264],
       [0.45788455, 0.54211545],
       [0.9218605 , 0.0781395 ],
       [0.89217285, 0.10782715],
       [0.84039959, 0.15960041],
       [0.89584512, 0.10415488],
       [0.86341511, 0.13658489],
       [0.61185438, 0.38814562],
       [0.75658169, 0.24341831],
       [0.43851544, 0.56148456],
       [0.89294273, 0.10705727],
       [0.84183224, 0.15816776],
       [0.82412554, 0.17587446],
       [0.73837335, 0.26162665],
       [0.55354962, 0.44645038],
       [0.91214976, 0.08785024],
       [0.54312582, 0.45687418],
       [0.80967417, 0.19032583],
       [0.57191501, 0.42808499],
       [0.89932473, 0.10067527],
       [0.49436913, 0.50563087],
       [0.83955737, 0.16044263],
       [0.84122086, 0.15877914],
       [0.88095507, 0.11904493],
       [0.78033306, 0.21966694],
       [0.71415875, 0.28584125],
       [0.86138994, 0.13861006],
       [0.89705008, 0.10294992],
       [0.87380138, 0.12619862],
       [0.90852567, 0.09147433],
       [0.90446444, 0.09553556],
       [0.74256078, 0.25743922],
       [0.85894563, 0.14105437],
       [0.68417591, 0.31582409],
       [0.91249017, 0.08750983],
       [0.87940951, 0.12059049],
       [0.76485311, 0.23514689],
       [0.79053795, 0.20946205],
       [0.72259996, 0.27740004],
       [0.88062356, 0.11937644],
       [0.88697957, 0.11302043],
       [0.88698422, 0.11301578],
       [0.81694794, 0.18305206],
       [0.37128216, 0.62871784],
       [0.89292337, 0.10707663],
       [0.89300587, 0.10699413],
       [0.87322393, 0.12677607],
       [0.83243923, 0.16756077],
       [0.83953627, 0.16046373],
       [0.92532084, 0.07467916],
       [0.66706932, 0.33293068],
       [0.85506257, 0.14493743],
       [0.89668099, 0.10331901],
       [0.8186757 , 0.1813243 ],
       [0.71556874, 0.28443126],
       [0.82261426, 0.17738574],
       [0.88851757, 0.11148243],
       [0.70810156, 0.29189844],
       [0.84825899, 0.15174101],
       [0.89226029, 0.10773971],
       [0.89449875, 0.10550125],
       [0.83405128, 0.16594872],
       [0.79897534, 0.20102466],
       [0.77223428, 0.22776572],
       [0.87885886, 0.12114114],
       [0.70911817, 0.29088183],
       [0.89723212, 0.10276788],
       [0.91225995, 0.08774005],
       [0.62320304, 0.37679696],
       [0.9189394 , 0.0810606 ],
       [0.69542647, 0.30457353],
       [0.90314972, 0.09685028],
       [0.8731297 , 0.1268703 ],
       [0.73962622, 0.26037378],
       [0.71673291, 0.28326709],
       [0.85104001, 0.14895999],
       [0.82667017, 0.17332983],
       [0.90671113, 0.09328887],
       [0.82075983, 0.17924017]])

In [236]:
list=[]
for i in range(len(probs)):
    list.append(probs[i][0])
print(list)

[0.8004665490033066, 0.8203927114443733, 0.7771726676631101, 0.5330080387036525, 0.8529231356850189, 0.8174465843468378, 0.8089721060335289, 0.8654801811637763, 0.8546670770495158, 0.8726563750980614, 0.8327431120441424, 0.8364834125083429, 0.790508080108503, 0.6610881039669831, 0.8894077296981857, 0.7805994851546163, 0.7901623765290196, 0.8372038316758272, 0.675526162154781, 0.7982736395790004, 0.8039949187601734, 0.8578650205113805, 0.9072535200523815, 0.825537092537543, 0.7853900332901257, 0.8067105158383745, 0.7067776444976351, 0.8835181692566993, 0.8195571759714718, 0.7851831587726964, 0.8271977571644474, 0.8424960384114171, 0.8095250477914153, 0.7140306525335134, 0.8469816220551966, 0.7940935062331307, 0.7782145213189233, 0.569646226878054, 0.9070320945612029, 0.8419013668883752, 0.8735319645071296, 0.8045979487729659, 0.7942288507504718, 0.881381621811984, 0.8241316294826428, 0.8470806062353893, 0.7878797275408271, 0.7066546271530899, 0.9132695743651652, 0.8644882379642581, 0.9071068040921165, 0.7095103077974367, 0.7901992695505782, 0.8176782585671621, 0.7897899104833711, 0.8525665688055135, 0.8308383174848324, 0.8934406613031989, 0.7639584852672882, 0.7013505506085594, 0.7147274569071982, 0.8492077663008998, 0.8815760018905432, 0.8725419181516267, 0.7773347400949396, 0.8606764269517286, 0.8065010168364992, 0.847748519314327, 0.7942434236470176, 0.8640418427920151, 0.7321817209745182, 0.7025891593253187, 0.8351301329713283, 0.7730219910128313, 0.7822774052445319, 0.7486505117018051, 0.8372486533974768, 0.6866344455712736, 0.8224730145211264, 0.8749346635307539, 0.9021932626886336, 0.7267580986388603, 0.6818821710723425, 0.8284779407058616, 0.6936027839347141, 0.7901373851841711, 0.8095385108522102, 0.7631492098736017, 0.8850840199657, 0.6928000704418278, 0.8444461720578073, 0.7047539266436387, 0.8135081195362504, 0.8074488616211073, 0.9213867285156033, 0.8068352877628875, 0.7573081560682411, 0.5939483618298954, 0.7589687058778736, 0.7638772055463767, 0.9004954117152556, 0.8089081722803503, 0.7901417858326653, 0.8651384206606494, 0.6654925511021403, 0.8263133118892887, 0.7303997780011833, 0.777795316149264, 0.9201575018629014, 0.855830193411873, 0.8712905032365466, 0.8821406683443022, 0.7135560868581163, 0.8245162692497682, 0.8349734906073779, 0.7238876008484744, 0.8370570449021731, 0.8257035499387029, 0.6741494698966293, 0.6162700904424353, 0.7928296352330071, 0.8871997898671272, 0.8660937402527739, 0.814706738524495, 0.7917087966717757, 0.7683907766682393, 0.4801791633300157, 0.6948146485942003, 0.8824169024840581, 0.7575136624686778, 0.7605640214829905, 0.8346094595492138, 0.7496676609637251, 0.8675062247361557, 0.8183025352992943, 0.7832527006135337, 0.7570625154324638, 0.7015605419987376, 0.8376437005549339, 0.8344480242553245, 0.6227750379559276, 0.8341819883807271, 0.7819784240041544, 0.8923902354119843, 0.8224472477269219, 0.8389575271931891, 0.7054267021421056, 0.7218240724746517, 0.8370769894829815, 0.8529249914035375]

In [288]:
liste=pd.DataFrame(list)

In [294]:
predicts = pd.concat([X_test, liste], axis=1)

In [295]:
predicts.head()

,age,tauxPart,visiPlat,discussion,noteTalent,noteInst,F,M,Licence 3,Master 1,Master 2,cohorte 5,cohorte 6,cohorte 7,Dessous-7,Dessus-7,Dessous-3,Dessus-3,id,0
0,18.0,29.0,16.0,20.0,19.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,3711.0,0.800467
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.820393
2,18.0,14.0,7.0,30.0,16.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,4420.0,0.777173
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.533008
4,18.0,38.0,50.0,50.0,6.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,5320.0,0.852923

In [298]:
drop=predicts.dropna()

,age,tauxPart,visiPlat,discussion,noteTalent,noteInst,F,M,Licence 3,Master 1,Master 2,cohorte 5,cohorte 6,cohorte 7,Dessous-7,Dessus-7,Dessous-3,Dessus-3,id,0
0,18.0,29.0,16.0,20.0,19.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,3711.0,0.800467
2,18.0,14.0,7.0,30.0,16.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,4420.0,0.777173
4,18.0,38.0,50.0,50.0,6.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,5320.0,0.852923
5,30.0,4.0,30.0,70.0,3.0,17.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,417.0,0.817447
7,30.0,46.0,10.0,22.0,11.0,9.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,4004.0,0.865480
8,24.0,16.0,21.0,50.0,19.0,3.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,4712.0,0.854667
13,24.0,30.0,14.0,19.0,6.0,20.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,8849.0,0.661088
18,24.0,47.0,15.0,96.0,17.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,6702.0,0.675526
19,24.0,23.0,50.0,99.0,20.0,13.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,6773.0,0.798274
25,24.0,10.0,7.0,40.0,1.0,14.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,2328.0,0.806711
28,24.0,13.0,85.0,43.0,13.0,10.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1066.0,0.819557
35,24.0,11.0,12.0,30.0,7.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,2623.0,0.794094
38,24.0,4.0,0.0,4.0,12.0,16.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1878.0,0.907032
46,24.0,35.0,10.0,30.0,16.0,9.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,9534.0,0.787880
49,22.0,19.0,39.0,77.0,4.0,6.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,3806.0,0.864488
50,24.0,23.0,14.0,70.0,8.0,14.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1451.0,0.907107
51,24.0,26.0,15.0,50.0,20.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,2040.0,0.709510
52,24.0,7.0,90.0,40.0,2.0,16.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,5620.0,0.790199
54,18.0,23.0,50.0,30.0,18.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,7689.0,0.789790
57,24.0,15.0,2.0,5.0,11.0,11.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,115.0,0.893441
58,24.0,14.0,60.0,50.0,8.0,10.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,9922.0,0.763958
60,26.0,49.0,10.0,20.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,2277.0,0.714727
64,24.0,28.0,5.0,2.0,19.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,5140.0,0.777335
66,24.0,45.0,10.0,30.0,0.0,10.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,9755.0,0.806501
68,24.0,19.0,69.0,30.0,8.0,18.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,6467.0,0.794243
73,28.0,25.0,30.0,19.0,16.0,17.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,183.0,0.773022
78,24.0,23.0,3.0,9.0,5.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,4929.0,0.822473
82,24.0,31.0,5.0,80.0,1.0,10.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,8302.0,0.681882
84,24.0,31.0,70.0,10.0,3.0,4.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,907.0,0.693603
87,24.0,16.0,70.0,50.0,8.0,12.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,6610.0,0.763149
90,24.0,49.0,8.0,60.0,15.0,17.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,2948.0,0.844446
91,25.0,50.0,90.0,19.0,5.0,8.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,6360.0,0.704754
96,24.0,42.0,60.0,75.0,11.0,17.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,9758.0,0.757308
101,24.0,30.0,92.0,7.0,6.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,7946.0,0.808908
103,24.0,9.0,7.0,10.0,11.0,4.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1677.0,0.865138
111,24.0,15.0,80.0,80.0,16.0,7.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,3137.0,0.882141
119,24.0,23.0,60.0,60.0,9.0,14.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,3922.0,0.616270
125,24.0,7.0,30.0,17.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,644.0,0.768391
126,24.0,31.0,9.0,55.0,19.0,7.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,2731.0,0.480179
133,24.0,46.0,60.0,70.0,3.0,9.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,3456.0,0.867506
134,27.0,17.0,80.0,70.0,8.0,14.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,4469.0,0.818303
136,26.0,28.0,80.0,70.0,14.0,5.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,4326.0,0.757063
137,24.0,41.0,80.0,40.0,13.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,7218.0,0.701561
142,23.0,27.0,75.0,11.0,19.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,5978.0,0.781978
144,23.0,20.0,10.0,19.0,17.0,19.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,2638.0,0.822447
149,24.0,8.0,75.0,70.0,8.0,13.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,7012.0,0.852925

In [309]:
drop=predicts.dropna()

In [310]:
drop.head()

,age,tauxPart,visiPlat,discussion,noteTalent,noteInst,F,M,Licence 3,Master 1,Master 2,cohorte 5,cohorte 6,cohorte 7,Dessous-7,Dessus-7,Dessous-3,Dessus-3,id,predictions
0,18.0,29.0,16.0,20.0,19.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,3711.0,0.800467
2,18.0,14.0,7.0,30.0,16.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,4420.0,0.777173
4,18.0,38.0,50.0,50.0,6.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,5320.0,0.852923
5,30.0,4.0,30.0,70.0,3.0,17.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,417.0,0.817447
7,30.0,46.0,10.0,22.0,11.0,9.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,4004.0,0.865480

In [303]:
predicts = predicts.rename(columns={0: 'predictions'})

In [304]:
predicts.head()

,age,tauxPart,visiPlat,discussion,noteTalent,noteInst,F,M,Licence 3,Master 1,Master 2,cohorte 5,cohorte 6,cohorte 7,Dessous-7,Dessus-7,Dessous-3,Dessus-3,id,predictions
0,18.0,29.0,16.0,20.0,19.0,2.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,3711.0,0.800467
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.820393
2,18.0,14.0,7.0,30.0,16.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,4420.0,0.777173
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.533008
4,18.0,38.0,50.0,50.0,6.0,5.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,5320.0,0.852923

In [311]:
resul = drop[['id','predictions']]

In [312]:
resul

         id  predictions
0    3711.0     0.800467
2    4420.0     0.777173
4    5320.0     0.852923
5     417.0     0.817447
7    4004.0     0.865480
8    4712.0     0.854667
13   8849.0     0.661088
18   6702.0     0.675526
19   6773.0     0.798274
25   2328.0     0.806711
28   1066.0     0.819557
35   2623.0     0.794094
38   1878.0     0.907032
46   9534.0     0.787880
49   3806.0     0.864488
50   1451.0     0.907107
51   2040.0     0.709510
52   5620.0     0.790199
54   7689.0     0.789790
57    115.0     0.893441
58   9922.0     0.763958
60   2277.0     0.714727
64   5140.0     0.777335
66   9755.0     0.806501
68   6467.0     0.794243
73    183.0     0.773022
78   4929.0     0.822473
82   8302.0     0.681882
84    907.0     0.693603
87   6610.0     0.763149
90   2948.0     0.844446
91   6360.0     0.704754
96   9758.0     0.757308
101  7946.0     0.808908
103  1677.0     0.865138
111  3137.0     0.882141
119  3922.0     0.616270
125   644.0     0.768391
126  2731.0     0.480179
133  3456.0     0.867506
134  4469.0     0.818303
136  4326.0     0.757063
137  7218.0     0.701561
142  5978.0     0.781978
144  2638.0     0.822447
149  7012.0     0.852925

In [318]:
id=resul['id']
id=pd.DataFrame(id)

In [321]:
 df.loc[df['id']==id]

ValueError: Cannot index with multidimensional key

In [313]:
add_score("Arbre", accuracy_train, accuracy_test)

     Modèle     Train      Test     Delta
0  Linéaire  0.811429  0.753333  0.058095
1     Arbre  0.851429  0.760000  0.091429

# Naive Bayes Classifier

In [80]:
nby = GaussianNB().fit(X_train, y_train)

In [81]:
prediction = nby.predict(X_train)

accuracy_train = accuracy_score(y_train, prediction)
accuracy_train

0.7914285714285715

In [82]:
prediction = nby.predict(X_test)

accuracy_test = accuracy_score(y_test, prediction)
accuracy_test

0.8266666666666667

In [84]:
add_score("Naive Bayes", accuracy_train, accuracy_test)

        Modèle     Train      Test     Delta
0     Linéaire  0.774286  0.773333  0.000952
1        Arbre  0.834286  0.806667  0.027619
2  Naive Bayes  0.791429  0.826667  0.035238

# Gradient Boosting Classifier

In [133]:
gbc = GradientBoostingClassifier(learning_rate=0.01, max_depth=2, random_state=0)
gbc = gbc.fit(X_train, y_train)

In [134]:
prediction = gbc.predict(X_train)

accuracy_train = accuracy_score(y_train, prediction)
accuracy_train

0.8114285714285714

In [135]:
prediction = gbc.predict(X_test)

accuracy_test = accuracy_score(y_test, prediction)
accuracy_test

0.8066666666666666

In [136]:
add_score("Gradient Boosting", accuracy_train, accuracy_test)

              Modèle     Train      Test     Delta
0           Linéaire  0.774286  0.773333  0.000952
1              Arbre  0.834286  0.806667  0.027619
2        Naive Bayes  0.791429  0.826667  0.035238
3  Gradient Boosting  0.811429  0.806667  0.004762